# Exported from Render on 2025-10-07T19:50:39Z
version: "1"
services:
- type: web
  name: work_items_tracker_BE
  runtime: python
  pythonVersion: 3.12.15
  repo: https://github.com/sugils-vdart/work_items_tracker_BE
  plan: free
  envVars:
  - key: env
    sync: false
  - key: DB_NAME
    sync: false
  - key: DB_PORT
    sync: false
  - key: DB_HOST
    sync: false
  - key: DB_PASSWORD
    sync: false
  - key: DB_USER
    sync: false
  region: oregon
  buildCommand: pip install -r requirements.txt
  startCommand: gunicorn app:app
  healthCheckPath: /healthz
  autoDeployTrigger: commit
